/*
 * LeanIX Metrics REST API
 * Stores and retrieves metrics
 *
 * OpenAPI spec version: 0.3.3-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.leanix.metrics.api.models;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * DemoDataRequest
 */

public class DemoDataRequest {
  @JsonProperty("demoDataType")
  private String demoDataType = null;

  @JsonProperty("workspaceId")
  private String workspaceId = null;

  @JsonProperty("measurement")
  private String measurement = null;

  @JsonProperty("tagKey")
  private String tagKey = null;

  @JsonProperty("tagValue")
  private String tagValue = null;

  public DemoDataRequest demoDataType(String demoDataType) {
    this.demoDataType = demoDataType;
    return this;
  }

   /**
   * The type of demo data series that has to be generate
   * @return demoDataType
  **/
  @ApiModelProperty(required = true, value = "The type of demo data series that has to be generate")
  public String getDemoDataType() {
    return demoDataType;
  }

  public void setDemoDataType(String demoDataType) {
    this.demoDataType = demoDataType;
  }

  public DemoDataRequest workspaceId(String workspaceId) {
    this.workspaceId = workspaceId;
    return this;
  }

   /**
   * A UUID string to relate the point to a workspace or \&quot;shared\&quot; if the shared database should be used.
   * @return workspaceId
  **/
  @ApiModelProperty(required = true, value = "A UUID string to relate the point to a workspace or \"shared\" if the shared database should be used.")
  public String getWorkspaceId() {
    return workspaceId;
  }

  public void setWorkspaceId(String workspaceId) {
    this.workspaceId = workspaceId;
  }

  public DemoDataRequest measurement(String measurement) {
    this.measurement = measurement;
    return this;
  }

   /**
   * A name for the measurement
   * @return measurement
  **/
  @ApiModelProperty(required = true, value = "A name for the measurement")
  public String getMeasurement() {
    return measurement;
  }

  public void setMeasurement(String measurement) {
    this.measurement = measurement;
  }

  public DemoDataRequest tagKey(String tagKey) {
    this.tagKey = tagKey;
    return this;
  }

   /**
   * The value for the tag the demo data point is assigned to
   * @return tagKey
  **/
  @ApiModelProperty(value = "The value for the tag the demo data point is assigned to")
  public String getTagKey() {
    return tagKey;
  }

  public void setTagKey(String tagKey) {
    this.tagKey = tagKey;
  }

  public DemoDataRequest tagValue(String tagValue) {
    this.tagValue = tagValue;
    return this;
  }

   /**
   * The name of the tag the demo data point is assigned to
   * @return tagValue
  **/
  @ApiModelProperty(value = "The name of the tag the demo data point is assigned to")
  public String getTagValue() {
    return tagValue;
  }

  public void setTagValue(String tagValue) {
    this.tagValue = tagValue;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DemoDataRequest demoDataRequest = (DemoDataRequest) o;
    return Objects.equals(this.demoDataType, demoDataRequest.demoDataType) &&
        Objects.equals(this.workspaceId, demoDataRequest.workspaceId) &&
        Objects.equals(this.measurement, demoDataRequest.measurement) &&
        Objects.equals(this.tagKey, demoDataRequest.tagKey) &&
        Objects.equals(this.tagValue, demoDataRequest.tagValue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(demoDataType, workspaceId, measurement, tagKey, tagValue);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DemoDataRequest {\n");
    
    sb.append("    demoDataType: ").append(toIndentedString(demoDataType)).append("\n");
    sb.append("    workspaceId: ").append(toIndentedString(workspaceId)).append("\n");
    sb.append("    measurement: ").append(toIndentedString(measurement)).append("\n");
    sb.append("    tagKey: ").append(toIndentedString(tagKey)).append("\n");
    sb.append("    tagValue: ").append(toIndentedString(tagValue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

