/*
 * LeanIX Metrics REST API
 * Stores and retrieves metrics
 *
 * OpenAPI spec version: 0.3.3-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.leanix.metrics.api.models;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import net.leanix.metrics.api.models.Field;
import net.leanix.metrics.api.models.Tag;

/**
 * Point
 */

public class Point {
  @JsonProperty("measurement")
  private String measurement = null;

  @JsonProperty("workspaceId")
  private String workspaceId = null;

  @JsonProperty("time")
  private OffsetDateTime time = null;

  @JsonProperty("tags")
  private List<Tag> tags = null;

  @JsonProperty("fields")
  private List<Field> fields = null;

  public Point measurement(String measurement) {
    this.measurement = measurement;
    return this;
  }

   /**
   * A name for the measurement
   * @return measurement
  **/
  @ApiModelProperty(value = "A name for the measurement")
  public String getMeasurement() {
    return measurement;
  }

  public void setMeasurement(String measurement) {
    this.measurement = measurement;
  }

  public Point workspaceId(String workspaceId) {
    this.workspaceId = workspaceId;
    return this;
  }

   /**
   * A UUID string to relate the point to a workspace or \&quot;shared\&quot; if the shared database should be used.
   * @return workspaceId
  **/
  @ApiModelProperty(value = "A UUID string to relate the point to a workspace or \"shared\" if the shared database should be used.")
  public String getWorkspaceId() {
    return workspaceId;
  }

  public void setWorkspaceId(String workspaceId) {
    this.workspaceId = workspaceId;
  }

  public Point time(OffsetDateTime time) {
    this.time = time;
    return this;
  }

   /**
   * Get time
   * @return time
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getTime() {
    return time;
  }

  public void setTime(OffsetDateTime time) {
    this.time = time;
  }

  public Point tags(List<Tag> tags) {
    this.tags = tags;
    return this;
  }

  public Point addTagsItem(Tag tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<Tag>();
    }
    this.tags.add(tagsItem);
    return this;
  }

   /**
   * List of tags
   * @return tags
  **/
  @ApiModelProperty(value = "List of tags")
  public List<Tag> getTags() {
    return tags;
  }

  public void setTags(List<Tag> tags) {
    this.tags = tags;
  }

  public Point fields(List<Field> fields) {
    this.fields = fields;
    return this;
  }

  public Point addFieldsItem(Field fieldsItem) {
    if (this.fields == null) {
      this.fields = new ArrayList<Field>();
    }
    this.fields.add(fieldsItem);
    return this;
  }

   /**
   * List of fields
   * @return fields
  **/
  @ApiModelProperty(value = "List of fields")
  public List<Field> getFields() {
    return fields;
  }

  public void setFields(List<Field> fields) {
    this.fields = fields;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Point point = (Point) o;
    return Objects.equals(this.measurement, point.measurement) &&
        Objects.equals(this.workspaceId, point.workspaceId) &&
        Objects.equals(this.time, point.time) &&
        Objects.equals(this.tags, point.tags) &&
        Objects.equals(this.fields, point.fields);
  }

  @Override
  public int hashCode() {
    return Objects.hash(measurement, workspaceId, time, tags, fields);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Point {\n");
    
    sb.append("    measurement: ").append(toIndentedString(measurement)).append("\n");
    sb.append("    workspaceId: ").append(toIndentedString(workspaceId)).append("\n");
    sb.append("    time: ").append(toIndentedString(time)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    fields: ").append(toIndentedString(fields)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

