/*
 * LeanIX Metrics REST API
 * Stores and retrieves metrics
 *
 * OpenAPI spec version: 0.3.3-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.leanix.metrics.api.models;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Tag
 */

public class Tag {
  @JsonProperty("k")
  private String k = null;

  @JsonProperty("v")
  private String v = null;

  public Tag k(String k) {
    this.k = k;
    return this;
  }

   /**
   * Tag key
   * @return k
  **/
  @ApiModelProperty(value = "Tag key")
  public String getK() {
    return k;
  }

  public void setK(String k) {
    this.k = k;
  }

  public Tag v(String v) {
    this.v = v;
    return this;
  }

   /**
   * Tag value
   * @return v
  **/
  @ApiModelProperty(value = "Tag value")
  public String getV() {
    return v;
  }

  public void setV(String v) {
    this.v = v;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Tag tag = (Tag) o;
    return Objects.equals(this.k, tag.k) &&
        Objects.equals(this.v, tag.v);
  }

  @Override
  public int hashCode() {
    return Objects.hash(k, v);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Tag {\n");
    
    sb.append("    k: ").append(toIndentedString(k)).append("\n");
    sb.append("    v: ").append(toIndentedString(v)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

