/*
 * LeanIX Metrics REST API
 * Stores and retrieves metrics
 *
 * OpenAPI spec version: 0.3.3-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.leanix.metrics.api.models;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * Value
 */

public class Value {
  @JsonProperty("t")
  private OffsetDateTime t = null;

  @JsonProperty("v")
  private List<Object> v = null;

  public Value t(OffsetDateTime t) {
    this.t = t;
    return this;
  }

   /**
   * Get t
   * @return t
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getT() {
    return t;
  }

  public void setT(OffsetDateTime t) {
    this.t = t;
  }

  public Value v(List<Object> v) {
    this.v = v;
    return this;
  }

  public Value addVItem(Object vItem) {
    if (this.v == null) {
      this.v = new ArrayList<Object>();
    }
    this.v.add(vItem);
    return this;
  }

   /**
   * Get v
   * @return v
  **/
  @ApiModelProperty(value = "")
  public List<Object> getV() {
    return v;
  }

  public void setV(List<Object> v) {
    this.v = v;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Value value = (Value) o;
    return Objects.equals(this.t, value.t) &&
        Objects.equals(this.v, value.v);
  }

  @Override
  public int hashCode() {
    return Objects.hash(t, v);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Value {\n");
    
    sb.append("    t: ").append(toIndentedString(t)).append("\n");
    sb.append("    v: ").append(toIndentedString(v)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

