/*
 * LeanIX Metrics REST API
 * Stores and retrieves metrics
 *
 * OpenAPI spec version: 0.3.3-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.leanix.metrics.api;

import net.leanix.dropkit.apiclient.ApiException;
import net.leanix.metrics.api.models.SeriesResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SeriesApi
 */
@Ignore
public class SeriesApiTest {

    private final SeriesApi api = new SeriesApi();

    
    /**
     * getSeries
     *
     * Endpoint to query results
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSeriesTest() throws ApiException {
        String q = null;
        String workspaceId = null;
        SeriesResponse response = api.getSeries(q, workspaceId);

        // TODO: test validations
    }
    
}
