/*
 * LeanIX Metrics REST API
 * Stores and retrieves metrics
 *
 * OpenAPI spec version: 0.3.3-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.leanix.metrics.api;

import net.leanix.dropkit.apiclient.ApiException;
import net.leanix.metrics.api.models.MeasurementResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for WorkspacesApi
 */
@Ignore
public class WorkspacesApiTest {

    private final WorkspacesApi api = new WorkspacesApi();

    
    /**
     * deleteMeasurementOfWorkspace
     *
     * Deletes all measurements of a workspace
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteMeasurementOfWorkspaceTest() throws ApiException {
        String wsId = null;
        MeasurementResponse response = api.deleteMeasurementOfWorkspace(wsId);

        // TODO: test validations
    }
    
}
